springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}11dcab8812ea05c5ecb4ac11f470fd1d5d8f08b50c85f63699eacbc66463a623'
    #password:
gateway:
  ip: 192.168.35.193