springbootwebfluxjjwt:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
spring:
  rabbitmq:
    host: 127.0.0.1
    username: user
    password: '{cipher}eebf968800a545119b8a02bfd8f6840280136886bdec98890346863fb6b20a84'
    #password:
gateway:
  ip: 192.168.35.193

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
